// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNboPe9CQ4Hd82T6rnrizNL5L7wu3uWdI',
    appId: '1:198873586173:web:96b8e57eff81ce15542194',
    messagingSenderId: '198873586173',
    projectId: 'smartfarm-6a1bf',
    authDomain: 'smartfarm-6a1bf.firebaseapp.com',
    storageBucket: 'smartfarm-6a1bf.firebasestorage.app',
    measurementId: 'G-BVDXHT9W71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHDuHP4Q-pJLh8aZhngMEPpD4daAGInv0',
    appId: '1:198873586173:android:0a10516c61675675542194',
    messagingSenderId: '198873586173',
    projectId: 'smartfarm-6a1bf',
    storageBucket: 'smartfarm-6a1bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCueRIH0Pd2oLajn0Crx0hcTEAj0bYk6xo',
    appId: '1:198873586173:ios:b58317bd21469c7c542194',
    messagingSenderId: '198873586173',
    projectId: 'smartfarm-6a1bf',
    storageBucket: 'smartfarm-6a1bf.firebasestorage.app',
    iosBundleId: 'com.example.plantHubProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCueRIH0Pd2oLajn0Crx0hcTEAj0bYk6xo',
    appId: '1:198873586173:ios:b58317bd21469c7c542194',
    messagingSenderId: '198873586173',
    projectId: 'smartfarm-6a1bf',
    storageBucket: 'smartfarm-6a1bf.firebasestorage.app',
    iosBundleId: 'com.example.plantHubProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNboPe9CQ4Hd82T6rnrizNL5L7wu3uWdI',
    appId: '1:198873586173:web:e43ed664f6d33747542194',
    messagingSenderId: '198873586173',
    projectId: 'smartfarm-6a1bf',
    authDomain: 'smartfarm-6a1bf.firebaseapp.com',
    storageBucket: 'smartfarm-6a1bf.firebasestorage.app',
    measurementId: 'G-NSD0SZR6B5',
  );
}
